import '@lkq-element-plus/components/base/style/css'
import '@lkq-element-plus/theme-chalk/el-table.css'
import '@lkq-element-plus/components/checkbox/style/css'
import '@lkq-element-plus/components/tag/style/css'
import '@lkq-element-plus/components/tooltip/style/css'
import '@lkq-element-plus/components/scrollbar/style/css'
